import { useEffect, useMemo, useState } from "react";
import { BookOpen, CalendarDays, CircleDollarSign, Clock3, FileText, LayoutDashboard, LogOut, Settings2, Sparkles, UsersRound } from "lucide-react";

type AdminUser = { email: string; role: "owner" | "manager" };
type Service = { slug: string; name: string; description: string; priceNote: string; durationNote: string; enabled: boolean };
type Slot = { id: number; startsAt: string; endsAt: string; status: string; note?: string | null };
type Course = { id: number; title: string; description: string; priceNote: string; durationNote: string; enabled: boolean };
type Booking = { id: number; status: string; createdAt: string; fullName: string; email?: string | null; whatsapp: string; serviceName: string; startsAt?: string | null; paymentStatus?: string | null };
type PaymentConnection = { provider: string; status: "draft" | "pending" | "active" | "restricted" | "disabled"; accountLabel?: string | null; updatedAt?: string | null } | null;
type DashboardData = {
  overview: { activeServices: number; clientCount: number; pendingBookings: number; blockedNotifications: number; integrations: { mailing: string; payments: string; whatsapp: string } };
  services: Service[];
  availability: Slot[];
  courses: Course[];
  bookings: Booking[];
  bookingsTotal: number;
};

type Section = "Resumen" | "Agenda" | "Servicios" | "Reservas" | "Cursos" | "Pagos" | "Contenido";
const sections: Array<{ label: Section; icon: typeof LayoutDashboard }> = [
  { label: "Resumen", icon: LayoutDashboard }, { label: "Agenda", icon: CalendarDays }, { label: "Servicios", icon: Sparkles }, { label: "Reservas", icon: UsersRound }, { label: "Cursos", icon: BookOpen }, { label: "Pagos", icon: CircleDollarSign }, { label: "Contenido", icon: FileText },
];

async function request<T>(path: string, options?: RequestInit) {
  const response = await fetch(path, { credentials: "include", ...options });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error ?? "No fue posible completar la solicitud.");
  return data as T;
}

function PanelTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) {
  return <div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#a7616e]">{eyebrow}</p><h2 className="mt-2 font-serif text-3xl italic leading-none sm:text-4xl">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#715f65]">{text}</p></div>;
}

function LoginPanel({ onLogin }: { onLogin: (user: AdminUser) => void }) {
  const [email, setEmail] = useState("studio.nataliarodriguez@gmail.com");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setLoading(true); setError("");
    try { const data = await request<{ user: AdminUser }>("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); onLogin(data.user); }
    catch (loginError) { setError(loginError instanceof Error ? loginError.message : "No fue posible iniciar sesión."); }
    finally { setLoading(false); }
  }
  return <main className="min-h-screen bg-[#1e1719] px-5 py-8 text-[#20181a] sm:grid sm:place-items-center"><section className="mx-auto w-full max-w-md overflow-hidden rounded-[2rem] bg-[#fbf6f2] shadow-[0_24px_70px_rgba(0,0,0,.35)]"><div className="bg-[#281e21] px-8 py-9 text-[#f9e5e6]"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f6a1ae]">Natalia Rodríguez Studio</p><h1 className="mt-3 font-serif text-4xl italic leading-none">Panel privado</h1><p className="mt-4 text-sm leading-6 text-[#e9d5d6]">Gestiona tu agenda, servicios, reservas y próximos módulos desde un solo lugar.</p></div><form onSubmit={submit} className="space-y-5 px-8 py-8"><label className="block text-sm font-semibold">Correo<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" className="mt-2 w-full rounded-xl border border-[#d9c9c5] bg-white px-4 py-3 outline-none ring-[#ee7488] focus:ring-2" required /></label><label className="block text-sm font-semibold">Contraseña<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" className="mt-2 w-full rounded-xl border border-[#d9c9c5] bg-white px-4 py-3 outline-none ring-[#ee7488] focus:ring-2" required /></label>{error ? <p className="rounded-xl bg-[#fde9eb] px-3 py-2 text-sm text-[#a13647]">{error}</p> : null}<button disabled={loading} className="w-full rounded-xl bg-[#ed7186] px-4 py-3 font-bold text-[#2b171b] transition hover:bg-[#e85e78] disabled:cursor-wait disabled:opacity-70">{loading ? "Ingresando…" : "Entrar a mi administración"}</button><p className="text-center text-xs leading-5 text-[#76636a]">Acceso privado de staging. Tus credenciales no se comparten con la operación central de ANC.</p></form></section></main>;
}

export default function NataliaAdmin() {
  const [user, setUser] = useState<AdminUser | null>(null);
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [checking, setChecking] = useState(true);
  const [active, setActive] = useState<Section>("Resumen");
  const [notice, setNotice] = useState("");
  const [saving, setSaving] = useState(false);
  const [serviceDraft, setServiceDraft] = useState<Service | null>(null);
  const [slotDraft, setSlotDraft] = useState({ startsAt: "", endsAt: "", note: "" });
  const [courseDraft, setCourseDraft] = useState({ title: "", description: "", priceNote: "", durationNote: "", enabled: false });
  const [paymentConnection, setPaymentConnection] = useState<PaymentConnection>(null);
  const [paymentLoading, setPaymentLoading] = useState(false);
  const [paymentError, setPaymentError] = useState("");
  const [visibleBookings, setVisibleBookings] = useState<Booking[]>([]);
  const [bookingsLoading, setBookingsLoading] = useState(false);

  async function loadDashboard() {
    const data = await request<DashboardData>("/api/admin/dashboard");
    setDashboard(data); setVisibleBookings(data.bookings); setServiceDraft((current) => current ?? data.services[0] ?? null);
  }
  async function loadPaymentConnection() {
    try { const data = await request<{ connection: PaymentConnection }>("/api/admin/payments/mercadopago"); setPaymentConnection(data.connection); setPaymentError(""); }
    catch (error) { setPaymentError(error instanceof Error ? error.message : "No fue posible consultar la conexión de pagos."); }
  }
  useEffect(() => { request<{ user: AdminUser }>("/api/admin/me").then(async (data) => { setUser(data.user); await Promise.all([loadDashboard(), loadPaymentConnection()]); }).catch(() => setUser(null)).finally(() => setChecking(false)); }, []);
  async function signOut() { await request("/api/admin/logout", { method: "POST" }); setUser(null); setDashboard(null); }
  async function mutate(path: string, body: unknown, success: string) { setSaving(true); setNotice(""); try { await request(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); await loadDashboard(); setNotice(success); } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible guardar los cambios."); } finally { setSaving(false); } }
  const overview = dashboard?.overview;
  const metrics = useMemo(() => [{ label: "Servicios activos", value: overview?.activeServices ?? 0, icon: Sparkles }, { label: "Solicitudes pendientes", value: overview?.pendingBookings ?? 0, icon: CalendarDays }, { label: "Pacientes registrados", value: overview?.clientCount ?? 0, icon: UsersRound }, { label: "Notificaciones bloqueadas", value: overview?.blockedNotifications ?? 0, icon: FileText }], [overview]);
  async function connectMercadoPago() {
    setPaymentLoading(true); setPaymentError("");
    try { const data = await request<{ authorizationUrl: string; connectionStatus: "pending" }>("/api/admin/payments/mercadopago/connect", { method: "POST" }); setPaymentConnection({ provider: "mercado_pago", status: data.connectionStatus }); window.location.assign(data.authorizationUrl); }
    catch (error) { setPaymentError(error instanceof Error ? error.message : "No fue posible iniciar la conexión de Mercado Pago."); }
    finally { setPaymentLoading(false); }
  }
  async function loadMoreBookings() {
    setBookingsLoading(true);
    try {
      const data = await request<{ bookings: Booking[]; total: number }>(`/api/admin/bookings?limit=50&offset=${visibleBookings.length}`);
      setVisibleBookings((current) => [...current, ...data.bookings.filter((booking) => !current.some((existing) => existing.id === booking.id))]);
    } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible cargar más reservas."); }
    finally { setBookingsLoading(false); }
  }
  if (checking) return <main className="grid min-h-screen place-items-center bg-[#1e1719] text-[#f9e5e6]">Cargando tu espacio privado…</main>;
  if (!user) return <LoginPanel onLogin={async (loggedUser) => { setUser(loggedUser); await Promise.all([loadDashboard(), loadPaymentConnection()]); }} />;
  const shortDate = (value: string) => new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
  return <main className="min-h-screen bg-[#f7f1ec] text-[#241b1d]"><header className="sticky top-0 z-20 flex items-center justify-between border-b border-[#dacbc6] bg-[#f7f1ec]/95 px-5 py-4 backdrop-blur sm:px-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#2b2022] font-serif text-lg italic text-[#f6b7c0]">Nr</span><div><p className="font-serif text-lg leading-none">Natalia Rodríguez</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.15em] text-[#9a5964]">Administración privada</p></div></div><button onClick={signOut} className="inline-flex items-center gap-2 rounded-full border border-[#cbb8b3] px-3 py-2 text-xs font-bold hover:bg-white"><LogOut size={14} /> Salir</button></header><div className="mx-auto grid max-w-7xl gap-6 px-5 py-6 lg:grid-cols-[220px_minmax(0,1fr)] lg:px-8"><aside className="rounded-3xl bg-[#2a2022] p-4 text-[#f8e9e8] lg:sticky lg:top-24 lg:h-fit"><p className="px-3 pb-4 text-xs text-[#d7b2b5]">{user.email}</p><nav className="grid grid-cols-2 gap-1 sm:grid-cols-4 lg:block">{sections.map(({ label, icon: Icon }) => <button key={label} onClick={() => setActive(label)} className={`flex w-full items-center gap-2 rounded-xl px-3 py-3 text-left text-sm transition ${active === label ? "bg-[#ed7186] font-bold text-[#28181b]" : "hover:bg-white/10"}`}><Icon size={16} />{label}</button>)}</nav><div className="mt-5 rounded-2xl border border-[#735d61] px-3 py-4 text-xs leading-5 text-[#d9c2c5]"><Settings2 size={15} className="mb-2" />Neon staging conectado. Mercado Pago se administra centralmente en ANC; este portal solo mostrará sus estados de pago.</div></aside><section className="space-y-6"><div className="rounded-3xl bg-[#e97486] p-7 text-[#2b171b] sm:flex sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em]">{active}</p><h1 className="mt-3 max-w-2xl font-serif text-4xl italic leading-[.95] sm:text-5xl">{active === "Resumen" ? "Tu negocio, en un solo lugar." : `Gestiona ${active.toLowerCase()} con claridad.`}</h1></div><div className="mt-5 rounded-2xl bg-[#f9d95d] px-4 py-3 text-sm font-bold sm:mt-0"><Clock3 size={16} className="mr-2 inline" />Staging activo</div></div>{notice ? <button onClick={() => setNotice("")} className="w-full rounded-2xl bg-[#fff1d2] px-4 py-3 text-left text-sm text-[#59411b]">{notice} ×</button> : null}
      {active === "Resumen" && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, icon: Icon }) => <article key={label} className="rounded-2xl border border-[#decfca] bg-white p-5"><Icon size={19} className="text-[#d85e73]" /><p className="mt-6 text-3xl font-bold">{value}</p><p className="mt-1 text-sm text-[#756269]">{label}</p></article>)}</div><div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-[#decfca] bg-white p-6"><PanelTitle eyebrow="Catálogo público" title="Servicios activos" text="Los cambios que guardes aquí alimentan el catálogo de tu landing de staging." /><div className="mt-5 space-y-3">{dashboard?.services.map((service) => <button key={service.slug} onClick={() => { setServiceDraft(service); setActive("Servicios"); }} className="block w-full rounded-2xl bg-[#f8f1ed] p-4 text-left hover:bg-[#f0e2dd]"><b>{service.name}</b><p className="mt-1 text-sm text-[#6f5e65]">{service.priceNote} · {service.durationNote}</p></button>)}</div></section><section className="rounded-3xl bg-[#2a2022] p-6 text-[#f8e9e8]"><PanelTitle eyebrow="Siguiente paso" title="Publica tus horarios" text="Crea slots disponibles para comenzar a convertir visitas en reservas dentro del sitio." /><button onClick={() => setActive("Agenda")} className="mt-6 rounded-full bg-[#ed7186] px-4 py-2 text-xs font-bold text-[#28181b]">Ir a agenda</button></section></div></>}
      {active === "Servicios" && <section className="rounded-3xl border border-[#decfca] bg-white p-6"><PanelTitle eyebrow="Catálogo" title="Edita tu servicio" text="Esta información aparece en la experiencia pública de staging." />{serviceDraft ? <form onSubmit={(event) => { event.preventDefault(); mutate("/api/admin/services", serviceDraft, "Servicio actualizado en staging."); }} className="mt-6 grid gap-4"><label className="text-sm font-bold">Nombre<input value={serviceDraft.name} onChange={(event) => setServiceDraft({ ...serviceDraft, name: event.target.value })} className="mt-2 w-full rounded-xl border border-[#decfca] px-3 py-3" /></label><label className="text-sm font-bold">Descripción<textarea value={serviceDraft.description} onChange={(event) => setServiceDraft({ ...serviceDraft, description: event.target.value })} className="mt-2 min-h-28 w-full rounded-xl border border-[#decfca] px-3 py-3" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Precio<input value={serviceDraft.priceNote} onChange={(event) => setServiceDraft({ ...serviceDraft, priceNote: event.target.value })} className="mt-2 w-full rounded-xl border border-[#decfca] px-3 py-3" /></label><label className="text-sm font-bold">Duración<input value={serviceDraft.durationNote} onChange={(event) => setServiceDraft({ ...serviceDraft, durationNote: event.target.value })} className="mt-2 w-full rounded-xl border border-[#decfca] px-3 py-3" /></label></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={serviceDraft.enabled} onChange={(event) => setServiceDraft({ ...serviceDraft, enabled: event.target.checked })} />Mostrar este servicio en la landing</label><button disabled={saving} className="w-fit rounded-full bg-[#2a2022] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving ? "Guardando…" : "Guardar servicio"}</button></form> : <p className="mt-5 text-sm">No hay servicios creados todavía.</p>}</section>}
      {active === "Agenda" && <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-3xl bg-[#2a2022] p-6 text-[#f8e9e8]"><PanelTitle eyebrow="Disponibilidad" title="Abre un horario" text="Los horarios disponibles serán la base de las futuras reservas pagadas." /><form onSubmit={(event) => { event.preventDefault(); mutate("/api/admin/availability", { ...slotDraft, startsAt: new Date(slotDraft.startsAt).toISOString(), endsAt: new Date(slotDraft.endsAt).toISOString() }, "Horario creado en staging."); setSlotDraft({ startsAt: "", endsAt: "", note: "" }); }} className="mt-6 space-y-4"><label className="block text-sm font-bold">Inicio<input required type="datetime-local" value={slotDraft.startsAt} onChange={(event) => setSlotDraft({ ...slotDraft, startsAt: event.target.value })} className="mt-2 w-full rounded-xl bg-white px-3 py-3 text-[#2a2022]" /></label><label className="block text-sm font-bold">Término<input required type="datetime-local" value={slotDraft.endsAt} onChange={(event) => setSlotDraft({ ...slotDraft, endsAt: event.target.value })} className="mt-2 w-full rounded-xl bg-white px-3 py-3 text-[#2a2022]" /></label><label className="block text-sm font-bold">Nota interna<input value={slotDraft.note} onChange={(event) => setSlotDraft({ ...slotDraft, note: event.target.value })} className="mt-2 w-full rounded-xl bg-white px-3 py-3 text-[#2a2022]" /></label><button disabled={saving} className="rounded-full bg-[#ed7186] px-5 py-3 text-sm font-bold text-[#28181b]">Crear horario</button></form></section><section className="rounded-3xl border border-[#decfca] bg-white p-6"><PanelTitle eyebrow="Próximos cupos" title="Tu agenda disponible" text="Los cupos se mantienen aislados en staging hasta activar el pago real." /><div className="mt-5 space-y-3">{dashboard?.availability.length ? dashboard.availability.map((slot) => <article key={slot.id} className="rounded-2xl bg-[#f8f1ed] p-4"><div className="flex items-center justify-between gap-3"><p className="font-bold">{shortDate(slot.startsAt)}</p><span className="rounded-full bg-[#e5f1df] px-2 py-1 text-xs font-bold text-[#356038]">{slot.status}</span></div><p className="mt-1 text-sm text-[#715f65]">Hasta {shortDate(slot.endsAt)}{slot.note ? ` · ${slot.note}` : ""}</p></article>) : <p className="rounded-2xl bg-[#f8f1ed] p-4 text-sm text-[#715f65]">Aún no hay horarios abiertos.</p>}</div></section></div>}
      {active === "Cursos" && <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-3xl bg-[#fff1d2] p-6"><PanelTitle eyebrow="Formación" title="Crea un curso" text="Los cursos quedan configurados en staging; el cobro y acceso se activarán cuando autorices esos módulos." /><form onSubmit={(event) => { event.preventDefault(); mutate("/api/admin/courses", courseDraft, "Curso guardado en staging."); setCourseDraft({ title: "", description: "", priceNote: "", durationNote: "", enabled: false }); }} className="mt-6 space-y-3"><input required placeholder="Título del curso" value={courseDraft.title} onChange={(event) => setCourseDraft({ ...courseDraft, title: event.target.value })} className="w-full rounded-xl border border-[#dfc78c] bg-white px-3 py-3" /><textarea placeholder="Descripción" value={courseDraft.description} onChange={(event) => setCourseDraft({ ...courseDraft, description: event.target.value })} className="min-h-24 w-full rounded-xl border border-[#dfc78c] bg-white px-3 py-3" /><div className="grid gap-3 sm:grid-cols-2"><input required placeholder="Precio" value={courseDraft.priceNote} onChange={(event) => setCourseDraft({ ...courseDraft, priceNote: event.target.value })} className="rounded-xl border border-[#dfc78c] bg-white px-3 py-3" /><input placeholder="Duración" value={courseDraft.durationNote} onChange={(event) => setCourseDraft({ ...courseDraft, durationNote: event.target.value })} className="rounded-xl border border-[#dfc78c] bg-white px-3 py-3" /></div><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={courseDraft.enabled} onChange={(event) => setCourseDraft({ ...courseDraft, enabled: event.target.checked })} />Mostrar como próximo curso</label><button disabled={saving} className="rounded-full bg-[#2a2022] px-5 py-3 text-sm font-bold text-white">Guardar curso</button></form></section><section className="rounded-3xl border border-[#decfca] bg-white p-6"><PanelTitle eyebrow="Oferta creada" title="Tus cursos" text="Editaremos contenido y acceso de estudiantes en el módulo de cursos." /><div className="mt-5 space-y-3">{dashboard?.courses.length ? dashboard.courses.map((course) => <article key={course.id} className="rounded-2xl bg-[#f8f1ed] p-4"><b>{course.title}</b><p className="mt-1 text-sm text-[#715f65]">{course.description || "Sin descripción"}</p><p className="mt-3 text-xs font-bold text-[#a45563]">{course.priceNote} · {course.durationNote || "Duración por definir"}</p></article>) : <p className="rounded-2xl bg-[#f8f1ed] p-4 text-sm text-[#715f65]">Aún no hay cursos creados.</p>}</div></section></div>}
      {active === "Reservas" && <section className="rounded-3xl border border-[#decfca] bg-white p-6"><PanelTitle eyebrow="Reservas" title="Solicitudes y confirmaciones" text="Cada reserva muestra el paciente, servicio, horario y el estado temporal mientras ANC habilita el checkout central." /><div className="mt-6 overflow-hidden rounded-2xl border border-[#e5d9d3]"><div className="grid grid-cols-[1.1fr_.85fr_.85fr_.7fr] gap-3 bg-[#f0e3de] px-4 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-[#745e64]"><span>Paciente</span><span>Servicio</span><span>Horario</span><span>Estado</span></div>{visibleBookings.length ? visibleBookings.map((booking) => <div key={booking.id} className="grid grid-cols-[1.1fr_.85fr_.85fr_.7fr] gap-3 border-t border-[#eee3de] px-4 py-4 text-sm"><div><b>{booking.fullName}</b><p className="mt-1 text-xs text-[#735f66]">{booking.email || booking.whatsapp}</p></div><p>{booking.serviceName}</p><p>{booking.startsAt ? shortDate(booking.startsAt) : "Por coordinar"}</p><div><span className="inline-block rounded-full bg-[#fff0bc] px-2 py-1 text-xs font-bold">{booking.paymentStatus === "simulated" ? "Prueba" : booking.paymentStatus || booking.status}</span></div></div>) : <p className="p-5 text-sm text-[#715f65]">Todavía no hay reservas registradas. Cuando una persona complete el flujo de prueba desde la landing aparecerá aquí.</p>}</div>{visibleBookings.length < (dashboard?.bookingsTotal ?? 0) ? <button onClick={loadMoreBookings} disabled={bookingsLoading} className="mt-5 rounded-full bg-[#2a2022] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{bookingsLoading ? "Cargando…" : `Ver más reservas (${dashboard!.bookingsTotal - visibleBookings.length})`}</button> : null}</section>}
      {active === "Pagos" && <section className="rounded-3xl bg-[#2a2022] p-7 text-[#f8e9e8]"><PanelTitle eyebrow="Pagos" title="Conecta tu cuenta" text="Autoriza tu propia cuenta de Mercado Pago en su pantalla oficial. ANC protege las credenciales, crea el checkout y mantiene la comisión acordada sin que este portal almacene claves." />{paymentError ? <p className="mt-5 rounded-2xl bg-[#5b2e36] px-4 py-3 text-sm text-[#ffe1e4]">{paymentError}</p> : null}<div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-4"><b>Proveedor</b><p className="mt-2 text-sm text-[#d7c1c4]">Mercado Pago vía ANC</p></div><div className="rounded-2xl bg-white/10 p-4"><b>Estado</b><p className="mt-2 text-sm text-[#d7c1c4]">{paymentConnection?.status === "active" ? "Cuenta autorizada" : paymentConnection?.status === "pending" ? "Autorización pendiente" : "Por conectar"}</p></div><div className="rounded-2xl bg-white/10 p-4"><b>Comisión ANC</b><p className="mt-2 text-sm text-[#d7c1c4]">Protegida y sin cambios</p></div></div><div className="mt-6 rounded-2xl border border-white/15 bg-white/5 p-4 text-sm leading-6 text-[#e2cfd1]"><b>Así funciona:</b> presiona el botón, ingresa directamente a Mercado Pago y aprueba la vinculación. ANC nunca recibe tu contraseña y este portal nunca guarda tokens.</div><button onClick={connectMercadoPago} disabled={paymentLoading} className="mt-5 rounded-full bg-[#ed7186] px-5 py-3 text-sm font-bold text-[#28181b] disabled:opacity-60">{paymentLoading ? "Abriendo Mercado Pago…" : paymentConnection?.status === "active" ? "Reconectar mi cuenta" : "Conectar mi cuenta de Mercado Pago"}</button></section>}
      {active === "Contenido" && <section className="rounded-3xl border border-[#decfca] bg-white p-6"><PanelTitle eyebrow="Contenido" title="Tu web, siempre actualizada" text="En el siguiente módulo podrás editar hero, biografía, FAQ y textos de cursos desde este mismo panel. El contenido público actual se mantiene protegido mientras definimos los permisos de publicación." /><button onClick={() => setNotice("La edición de contenido se agregará después de validar agenda y reservas.")} className="mt-6 rounded-full bg-[#2a2022] px-5 py-3 text-sm font-bold text-white">Ver próximos pasos</button></section>}
    </section></div></main>;
}
